### PR TITLE
Fix Java installation instructions for Mac OS

### PR DESCRIPTION
**Pull request by Ao-senXiong**

### CODE REVIEW

**Review by wmdietl — APPROVED** [review]
Thanks! Lots of posts use the @-less version...
https://formulae.brew.sh/cask/temurin@17 works and the @-less version doesn't work.
I don't have a Mac, so I can't try.

**Comment by Ao-senXiong** [comment]
> Thanks! Lots of posts use the @-less version... https://formulae.brew.sh/cask/temurin@17 works and the @-less version doesn't work. I don't have a Mac, so I can't try.

It must been updated, let's stick to the one in the link

**Comment by Ao-senXiong** [comment]
@wmdietl I think the change from this PR is gone since we fetch new changes from upstream.

**Comment by wmdietl** [comment]
> @wmdietl I think the change from this PR is gone since we fetch new changes from upstream.

Ah, sorry, looks like this was undone when I merged https://github.com/Ao-senXiong/checker-framework/commit/79670e2b950bf802dc74a02656b52a10979bb701#diff-ad5a739c6eede96b603a0a1bfbedc08260bfce4b3a724f7ebd4424c541106f54.

Can you open a new PR to fix this @Ao-senXiong ? There are two mentions of "temurin", should both be changed?
What about the "brew tap homebrew/cask-versions"?
Thanks!

**Pull request merged**
