### PR TITLE
Simplify the parameter checks for overrides.

### PR DESCRIPTION
**Pull request by cpovirk**
DO NOT MERGE, probably.

See discussion from about
https://github.com/jspecify/jspecify-reference-checker/issues/193#issuecomment-2253295876
onward.

This PR is a lazy way for me to run tests, since I don't trust myself to
find the right way to run them all locally.

### CODE REVIEW

**Comment by cpovirk** [comment]
For the record, for https://github.com/cpovirk/checker-framework/commit/85c2470666f5bcc2565ba768a6da5df6b81ae684 (`typeHierarchy.isSubtype(overriddenParams.get(i), overriderParams.get(i));` and nothing else), I'm seeing:

```
ERROR: internal error in type processor! method typeProcessOver() doesn't get called.
```

I might now test a variant of that.

**Comment by cpovirk** [comment]
...and the same problem if I put the `applyCaptureConversion` call back but remove the `testTypevarContainment` check.

I'm sure it could be interesting to dig deeper, but I'm just going to take away from this that there's no code that became trivially removable somewhere along the way.

**Comment by cpovirk** [comment]
OK, [that](https://github.com/eisop/checker-framework/pull/829/files/37d5a73bfe19d76549d4df8d81cf77f2201507d2)  version (which wasn't my [original](https://github.com/eisop/checker-framework/pull/829/commits/85c2470666f5bcc2565ba768a6da5df6b81ae684) version) [fails](https://github.com/eisop/checker-framework/actions/runs/11596046585/job/32286842840?pr=829) one [test](https://github.com/eisop/checker-framework/blob/33399f980cefe7ef14c85f25ddf05ba43083e4ea/checker/tests/i18n-formatter/I18nFormat.java#L18) that seems potentially unrelated:

```
I18nFormatterTest > run[D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter] FAILED
    java.lang.AssertionError: 69 out of 70 expected diagnostics were found.
    1 unexpected diagnostic was found:
      I18nFormat.java:18: error: (i18nformat.string.invalid)
    1 expected diagnostic was not found:
      I18nFormat.java:18: warning: (i18nformat.missing.arguments)
    While type-checking D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\ConversionCategoryTest.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\HasFormat.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\I18nFormat.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\I18nFormatForTest.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\IsFormat.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\ManualExampleI18nFormatter.java, D:\a\checker-framework\checker-framework\checker\tests\i18n-formatter\Syntax.java
```

I'm going to see what happens with the original version.

**Comment by wmdietl** [comment]
> OK, [that](https://github.com/eisop/checker-framework/pull/829/files/37d5a73bfe19d76549d4df8d81cf77f2201507d2) version (which wasn't my [original](https://github.com/eisop/checker-framework/pull/829/commits/85c2470666f5bcc2565ba768a6da5df6b81ae684) version) [fails](https://github.com/eisop/checker-framework/actions/runs/11596046585/job/32286842840?pr=829) one [test](https://github.com/eisop/checker-framework/blob/33399f980cefe7ef14c85f25ddf05ba43083e4ea/checker/tests/i18n-formatter/I18nFormat.java#L18) that seems potentially unrelated:

Yes, unfortunately CI currently fails on `master`, with that same test case, after I merged a green PR.
It seems to only occur on the MacOS/Windows tests, so I'm not sure yet what is going on.

**Comment by cpovirk** [comment]
Thanks.

It looks like the original version fails only in that similar way, so I think everything I've seen is still at least _compatible_ with the idea that this code could be simplified.

Anyway, I don't want to actively pick this up now; I just remembered seeing that the earlier CI failure had been fixed, so I figured I'd resurrect this PR for testing purposes. Whenever I get back to https://github.com/jspecify/jspecify-reference-checker/issues/193, I may end up wanting to push this forward, or I might not.

**Pull request closed without merging**
