### PR TITLE
Remove hack now that JSpecify uses newer gradle

### PR DESCRIPTION
**Pull request by Ao-senXiong**

### CODE REVIEW

**Review by wmdietl — APPROVED** [review]
Thanks!
Separately, can you make sure we have the right build dependencies in `build.gradle`?

**Comment by Ao-senXiong** [comment]
> Thanks! Separately, can you make sure we have the right build dependencies in `build.gradle`?

Sure, but I did not find jspecify clone related script in build.gradle, could you point it out to me?

**Comment by wmdietl** [comment]
> Sure, but I did not find jspecify clone related script in build.gradle, could you point it out to me?

So the issue may be that we don't do anything for JSpecify in the build.
We clone some other repos, e.g. here:
https://github.com/eisop/checker-framework/blob/f50cbe37321ffbdc62842ddf19970d85f6849ba2/build.gradle#L831

How about a similar task to clone JSpecify and add that as a dependency to the JSpecify test?
Please also review tasks `maybeCloneAndBuildDependencies` and `cloneAndBuildDependencies` and see whether we can make this nicer.
There is also this other clone task:
https://github.com/eisop/checker-framework/blob/f50cbe37321ffbdc62842ddf19970d85f6849ba2/framework/build.gradle#L83
So maybe have a general review of where we clone repos.

**Comment by Ao-senXiong** [comment]
> > Sure, but I did not find jspecify clone related script in build.gradle, could you point it out to me?
> 
> So the issue may be that we don't do anything for JSpecify in the build. We clone some other repos, e.g. here:
> 
> https://github.com/eisop/checker-framework/blob/f50cbe37321ffbdc62842ddf19970d85f6849ba2/build.gradle#L831
> 
> How about a similar task to clone JSpecify and add that as a dependency to the JSpecify test? Please also review tasks `maybeCloneAndBuildDependencies` and `cloneAndBuildDependencies` and see whether we can make this nicer. There is also this other clone task:
> 
> https://github.com/eisop/checker-framework/blob/f50cbe37321ffbdc62842ddf19970d85f6849ba2/framework/build.gradle#L83
> 
> 
> So maybe have a general review of where we clone repos.
Ok, got it. Thanks.

**Pull request merged**
