### PR TITLE
Test cases for conservative default with `AnnotatedFor("initialization")` does not work

### PR DESCRIPTION
**Pull request by Ao-senXiong**
Expected failure

### CODE REVIEW

**Comment by Ao-senXiong** [comment]
The error expected is not found, which means the master branch did not work correclty. 
```
AnnotatedForNullnessTest > run[/home/runner/work/checker-framework/checker-framework/checker/tests/nulless-conservative-defaults/annotatedfornullness] FAILED
    java.lang.AssertionError: 4 out of 4 expected diagnostics were found.
    1 unexpected diagnostic was found:
      AnnotatedForNullness.java:43: error: (argument.type.incompatible)
    While type-checking /home/runner/work/checker-framework/checker-framework/checker/tests/nulless-conservative-defaults/annotatedfornullness/AnnotatedForNullness.java
```

**Comment by wmdietl** [comment]
#987 is the PR against #985, which tries to fix #982.
Please add references between different PRs and issues to make navigation easier.

**Comment by wmdietl** [comment]
> The error expected is not found, which means the master branch did not work correclty.
> 
>     1 unexpected diagnostic was found:
>       AnnotatedForNullness.java:43: error: (argument.type.incompatible)

The error message is that an unexpected diagnostic was found, not that an expected error was not found.

Can you add better comments to your test case to make it clearer what the expected behavior is?
Is the mismatch still what should be expected?

**Comment by Ao-senXiong** [comment]
> > The error expected is not found, which means the master branch did not work correclty.
> > ```
> > 1 unexpected diagnostic was found:
> >   AnnotatedForNullness.java:43: error: (argument.type.incompatible)
> > ```
> 
> The error message is that an unexpected diagnostic was found, not that an expected error was not found.
> 
> Can you add better comments to your test case to make it clearer what the expected behavior is? Is the mismatch still what should be expected?

Oh sorry I made a mistake when explaining, please see the comment in test cases.

**Review by wmdietl — APPROVED** [review]
Thanks, test case looks good! I'll close this and look at #987.

**Pull request closed without merging**
