### PR TITLE
Use `hasAnnotation` for precise check in `PolyTypeScanner`

### PR DESCRIPTION
**Pull request by Ao-senXiong**
This is related to Ontology as it use the value to represent poly type qualifier.
https://github.com/opprop/ontology/pull/130

### CODE REVIEW

**Comment by wmdietl** [comment]
Note that the plume_lib CI test currently fails, for the same reason as https://github.com/opprop/checker-framework/pull/259
It seems related to the upgrade to Gradle 8.7 together with the CF gradle plugin being out of date.
I don't want to do the work-around from https://github.com/opprop/checker-framework/pull/259, but haven't found anything better yet. Can you take a look?

**Comment by Ao-senXiong** [comment]
> Note that the plume_lib CI test currently fails, for the same reason as [opprop#259](https://github.com/opprop/checker-framework/pull/259) It seems related to the upgrade to Gradle 8.7 together with the CF gradle plugin being out of date. I don't want to do the work-around from [opprop#259](https://github.com/opprop/checker-framework/pull/259), but haven't found anything better yet. Can you take a look?

Sure, looks like all problem are the same. Let me take a look.

**Comment by Ao-senXiong** [comment]
> Note that the plume_lib CI test currently fails, for the same reason as [opprop#259](https://github.com/opprop/checker-framework/pull/259) It seems related to the upgrade to Gradle 8.7 together with the CF gradle plugin being out of date. I don't want to do the work-around from [opprop#259](https://github.com/opprop/checker-framework/pull/259), but haven't found anything better yet. Can you take a look?

@wmdietl It looks like the gradle version 8.7 is incompatible with CF plugin. The most simple approach is to downgrade to 8.6.
image

**Comment by wmdietl** [comment]
Downgrading sounds good. Could you please do this for the affected `eisop-plume-lib` projects?

But before that, we should improve the CI for the `eisp-plume-lib` projects. E.g. https://github.com/eisop-plume-lib/bcel-util/pull/81 was automatically merged b/c CI was green. The build configuration contains the checkerframework-gradle-plugin, but it doesn't seem to run during CI. Or why is CI green there?

Can you first make a PR that improves CI, which will fail, then a PR that also downgrades gradle only. Then we first merge the downgrade and then the CI improvements.
Thanks!

**Comment by Ao-senXiong** [comment]
Looks like the agent is time out again for non JUnit test

**Pull request merged**
