### PR TITLE
Update EISOP version in examples

### PR DESCRIPTION
**Pull request by wmdietl**

### CODE REVIEW

**Comment by Ao-senXiong** [comment]
@wmdietl Maybe you could also update the one in the manual in this PR? https://github.com/eisop/checker-framework/blob/4b27a7368cdde54beb9f10df8547d28b4bffe23a/docs/manual/external-tools.tex#L814-L818

**Comment by wmdietl** [comment]
> @wmdietl Maybe you could also update the one in the manual in this PR?

Thanks for noticing this! All other references in that file were okay... maybe I made a mistake when updating from `eisop1` to `eisop2` and then that stuck around.

**Comment by Ao-senXiong** [comment]
> > @wmdietl Maybe you could also update the one in the manual in this PR?
> 
> Thanks for noticing this! All other references in that file were okay... maybe I made a mistake when updating from `eisop1` to `eisop2` and then that stuck around.

No problem. I think I added the build config that's why I remember. Even in the PR, it was outdated at that time. https://github.com/eisop/checker-framework/pull/905

**Comment by wmdietl** [comment]
> No problem. I think I added the build config that's why I remember. Even in the PR, it was outdated at that time. #905

Ah, the release script only looks for the previous version, not all old versions. So, from now on it should get updated automatically.

**Comment by wmdietl** [comment]
> No problem. I think I added the build config that's why I remember. Even in the PR, it was outdated at that time. #905

In the future, please make sure to only add references to the latest release. Then the release script should make sure the version stays updated.

**Pull request merged**
