### PR TITLE
Decode element annotations on variable declarations

### PR DESCRIPTION
**Pull request by wmdietl**
Fixes typetools 5075

### CODE REVIEW

**Comment by cpovirk** [comment]
```
error: Error when invoking constructor org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory(class org.checkerframework.common.basetype.BaseTypeChecker) on args [org.checkerframework.checker.nullness.KeyForSubchecker@d1ef2b2]; cause: TreeUtils.getMethod(org.checkerframework.framework.qual.DefaultQualifier, applyToSubpackages, 0): expected 1 match, found 0
  ; The Checker Framework crashed.  Please report the crash.
  Exception: org.checkerframework.javacutil.BugInCF: TreeUtils.getMethod(org.checkerframework.framework.qual.DefaultQualifier, applyToSubpackages, 0): expected 1 match, found 0; org.checkerframework.javacutil.BugInCF: TreeUtils.getMethod(org.checkerframework.framework.qual.DefaultQualifier, applyToSubpackages, 0): expected 1 match, found 0
        at org.checkerframework.javacutil.TreeUtils.getMethod(TreeUtils.java:929)
        at org.checkerframework.javacutil.TreeUtils.getMethod(TreeUtils.java:904)
        at org.checkerframework.framework.util.defaults.QualifierDefaults.<init>(QualifierDefaults.java:197)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.createQualifierDefaults(GenericAnnotatedTypeFactory.java:742)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.createAndInitQualifierDefaults(GenericAnnotatedTypeFactory.java:728)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:398)
        at org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.<init>(KeyForAnnotatedTypeFactory.java:97)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:331)
        at org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:305)
        at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:268)
        at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:257)
        at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:252)
        at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:95)
        at org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:892)
        at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:117)
        at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:110)
        at org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:843)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:170)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1419)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1376)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:972)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
  Caused by: java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:34)
        ... 31 more
  
  Underlying Exception: java.lang.Throwable; java.lang.Throwable
        at org.checkerframework.javacutil.BugInCF.<init>(BugInCF.java:34)
        at org.checkerframework.javacutil.TreeUtils.getMethod(TreeUtils.java:929)
        at org.checkerframework.javacutil.TreeUtils.getMethod(TreeUtils.java:904)
        at org.checkerframework.framework.util.defaults.QualifierDefaults.<init>(QualifierDefaults.java:197)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.createQualifierDefaults(GenericAnnotatedTypeFactory.java:742)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.createAndInitQualifierDefaults(GenericAnnotatedTypeFactory.java:728)
        at org.checkerframework.framework.type.GenericAnnotatedTypeFactory.postInit(GenericAnnotatedTypeFactory.java:398)
        at org.checkerframework.checker.nullness.KeyForAnnotatedTypeFactory.<init>(KeyForAnnotatedTypeFactory.java:97)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.checkerframework.common.basetype.BaseTypeChecker.invokeConstructorFor(BaseTypeChecker.java:331)
        at org.checkerframework.common.basetype.BaseTypeVisitor.createTypeFactory(BaseTypeVisitor.java:305)
        at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:268)
        at org.checkerframework.common.basetype.BaseTypeVisitor.<init>(BaseTypeVisitor.java:257)
        at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:252)
        at org.checkerframework.common.basetype.BaseTypeChecker.createSourceVisitor(BaseTypeChecker.java:95)
        at org.checkerframework.framework.source.SourceChecker.initChecker(SourceChecker.java:892)
        at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:117)
        at org.checkerframework.common.basetype.BaseTypeChecker.initChecker(BaseTypeChecker.java:110)
        at org.checkerframework.framework.source.SourceChecker.typeProcessingStart(SourceChecker.java:843)
        at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished(AbstractTypeProcessor.java:170)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished(ClientCodeWrapper.java:828)
        at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1419)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1376)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:972)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

I'll try to see if I can minimize that for you tomorrow if the cause doesn't jump out to you. Maybe I just built my checker wrong?

**Comment by cpovirk** [comment]
Oh, wait, that must be the thing I said about needing to update the `checker-qual` jar, too? Let me try that....

**Comment by cpovirk** [comment]
Sorry, my mistake. It works with the correct `checker-qual.jar`.

That fixes the problem for the target I tested against. I'll test more and then report back.

**Comment by cpovirk** [comment]
Thanks!

I'll look more at `getEmail()`. It occurs to me that I'm comparing an eisop 3.21.2 release to a typetools 3.21.3 release, so there could have been some fix new to 3.21.3.

Here's `extensionViewHolderDelegate`. I think it's what you're expecting?

```java
  private final ViewHolder.Delegate extensionViewHolderDelegate =
      (@Nullable Type type, ViewDef.@Nullable Type viewType, View view) -> {
        ...
      };
```

**Comment by cpovirk** [comment]
I don't see the `getEmail()` error with typetools 3.21.2, so it may somehow be something about this commit after all. I'll keep looking.

**Comment by cpovirk** [comment]
(Err, and I guess your PR had already incorporated the typetools 3.21.3 changes, anyway.)

**Comment by cpovirk** [comment]
(no error at https://github.com/eisop/checker-framework/commit/a0e2e1175bc859020b277cb16d6b7bbc88878a2e, either, so there's something about this PR.... Will try to minimize.)

**Comment by cpovirk** [comment]
I reran all tests after https://github.com/eisop/checker-framework/pull/193/commits/99bf7ce8c94d6696a8c15277cede489c57a7bcc1, and everything looks great! Ship it :)

**Comment by wmdietl** [comment]
Thanks for confirming the fix works!

**Pull request merged**
